# Copyright (c) 2024 Microsoft Corporation.
# Licensed under the MIT License

"""Module for loading MATLAB analyzer graph data into networkx format."""

import json
import logging
from pathlib import Path
from typing import Any

import networkx as nx

logger = logging.getLogger(__name__)

class MATLABGraphLoader:
    """Loads a graph from a MATLAB analyzer JSON output file."""
    
    def __init__(self, graph_file: Path | str):
        """
        Initialize the graph loader.
        
        Args:
            graph_file: Path to the graph.json file generated by the MATLAB analyzer
        """
        self.graph_file = Path(graph_file)
        self.graph = nx.DiGraph()
        
    def load(self) -> nx.DiGraph:
        """Load the graph from the JSON file.
        
        Returns:
        -------
        networkx.DiGraph
            The loaded directed graph
        """
        logger.info("Loading MATLAB graph from %s", self.graph_file)
        
        error_msg = f"Graph file not found: {self.graph_file}"
        if not self.graph_file.exists():
            raise FileNotFoundError(error_msg)
            
        try:
            with self.graph_file.open(encoding="utf-8") as f:
                graph_data = json.load(f)
            
            # Check if the graph data is nested under a 'graph' key
            if "graph" in graph_data and isinstance(graph_data["graph"], dict):
                graph_data = graph_data["graph"]
                
            # Add nodes with attributes
            for node in graph_data.get("nodes", []):
                self._add_node(node)
                
            # Add edges with attributes
            for edge in graph_data.get("edges", []):
                self._add_edge(edge)
                
            logger.info(
                "Successfully loaded graph with %d nodes and %d edges",
                len(self.graph.nodes),
                len(self.graph.edges),
            )
            
            return self.graph
            
        except json.JSONDecodeError as e:
            logger.exception("Failed to parse JSON file")
            raise
        except Exception as e:
            logger.exception("Error loading graph")
            raise
    
    def _add_node(self, node_data: dict[str, Any]) -> None:
        """Add a node to the graph with its attributes.
        
        Args:
            node_data: Dictionary containing node data with the following possible fields:
                - id: Unique identifier for the node (required)
                - name: Display name of the node
                - node_type: Type of the node (e.g., 'script', 'variable')
                - file_path: Path to the source file
                - code: Source code content (for code nodes)
                - range: Dictionary with 'start' and 'end' positions
                - parent_id: ID of the parent node (for nested nodes)
                - metadata: Additional metadata dictionary
        """
        node_id = node_data.get("id")
        if node_id is None:
            logger.warning("Node missing 'id' field, skipping")
            return
            
        # Include all relevant fields from the node data
        attrs = {
            "node_type": node_data.get("node_type", "unknown"),
            "name": node_data.get("name", ""),
            "file_path": node_data.get("file_path", ""),
            "code": node_data.get("code", ""),
            "range": node_data.get("range", {}),
            "parent_id": node_data.get("parent_id"),
            "metadata": node_data.get("metadata", {})
        }
        
        # Remove None values to keep the graph clean
        attrs = {k: v for k, v in attrs.items() if v is not None}
        
        self.graph.add_node(node_id, **attrs)
    
    def _add_edge(self, edge_data: dict[str, Any]) -> None:
        """Add an edge to the graph with its attributes.
        
        Args:
            edge_data: Dictionary containing edge data
        """
        source = edge_data.get("source_id")
        target = edge_data.get("target_id")
        
        if source is None or target is None:
            logger.warning("Edge missing source_id or target_id, skipping")
            return
            
        attrs = {
            "relationship": edge_data.get("relationship", "calls"),
            "weight": edge_data.get("weight", 1.0),
            "metadata": edge_data.get("metadata", {})
        }
        self.graph.add_edge(source, target, **attrs)
